/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サービス死活監視 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定言語で公開中のニュース記事一覧を返す (直近順) */
        get: operations["listNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定言語で公開中のニュース記事詳細を返す */
        get: operations["getNewsDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        NewsListResponse: {
            articles: components["schemas"]["NewsListItem"][];
        };
        /** @description 一覧レスポンス要素。title / summary は指定 lang の翻訳由来。body / source_url は含まない。
         *      */
        NewsListItem: {
            /** @description ULID。 */
            article_id: string;
            source: components["schemas"]["Source"];
            title: string;
            summary: string;
            tags: string[];
            /**
             * Format: date-time
             * @description 元記事 (RSS 由来) の公開日時。nullable。
             */
            source_published_at?: string;
            /**
             * Format: date-time
             * @description アプリ内で公開された日時 (承認時刻)。公開中記事では必ず値を持つ。
             */
            published_at: string;
        };
        /** @description 詳細レスポンス。title / summary / body は指定 lang の翻訳由来。
         *      */
        NewsDetail: {
            article_id: string;
            source: components["schemas"]["Source"];
            title: string;
            summary: string;
            body: string;
            tags: string[];
            source_url: string;
            /**
             * Format: date-time
             * @description 元記事 RSS 由来。nullable。
             */
            source_published_at?: string;
            /** Format: date-time */
            published_at: string;
        };
        /**
         * @description 対応言語コード。SSoT は news 内の domain.SupportedLangs。
         * @enum {string}
         */
        Lang: "ja" | "en";
        /**
         * @description 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
         *     news 側では永続化と公開 API で同値を引き継ぐ。
         *
         * @enum {string}
         */
        Source: "aws" | "google-cloud" | "azure" | "oci" | "other";
    };
    responses: never;
    parameters: {
        /** @description 翻訳言語。未指定・対応外は 400。 */
        LangQuery: components["schemas"]["Lang"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listNews: {
        parameters: {
            query: {
                /** @description 翻訳言語。未指定・対応外は 400。 */
                lang: components["parameters"]["LangQuery"];
                /** @description 取得件数 (1-100)。未指定・範囲外は 400。 */
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponse"];
                };
            };
            /** @description lang 未指定 / 対応外 / limit 不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNewsDetail: {
        parameters: {
            query: {
                /** @description 翻訳言語。未指定・対応外は 400。 */
                lang: components["parameters"]["LangQuery"];
            };
            header?: never;
            path: {
                /** @description ULID。 */
                articleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsDetail"];
                };
            };
            /** @description lang 未指定 / 対応外 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 記事が存在しない / 公開中でない / 指定 lang の翻訳が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
