// Code generated by asyncapi-codegen-tools from asyncapi.yaml; DO NOT EDIT.

package apinews

import (
	"time"
)

// ArticleCollectedEvent は newsfeed が記事 1 件分の収集と翻訳生成を完了した際に発行するイベント。
// subscriber: news (news_articles + news_article_translations を同一 tx で永続化)。
// ArticleID で冪等性を担保する (at-least-once)。
type ArticleCollectedEvent struct {
	ArticleID         string             `json:"article_id"`
	Source            string             `json:"source"`
	SourceURL         string             `json:"source_url"`
	Tags              []string           `json:"tags"`
	SourcePublishedAt *time.Time         `json:"source_published_at,omitempty"`
	Translations      []EventTranslation `json:"translations"`
}

// EventTranslation
type EventTranslation struct {
	Lang    string `json:"lang"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Body    string `json:"body"`
}

