// Package apinews provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apinews

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for Lang.
const (
	LangEn Lang = "en"
	LangJa Lang = "ja"
)

// Valid indicates whether the value is a known member of the Lang enum.
func (e Lang) Valid() bool {
	switch e {
	case LangEn:
		return true
	case LangJa:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	SourceAws         Source = "aws"
	SourceAzure       Source = "azure"
	SourceGoogleCloud Source = "google-cloud"
	SourceOci         Source = "oci"
	SourceOther       Source = "other"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case SourceAws:
		return true
	case SourceAzure:
		return true
	case SourceGoogleCloud:
		return true
	case SourceOci:
		return true
	case SourceOther:
		return true
	default:
		return false
	}
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Lang 対応言語コード。SSoT は news 内の domain.SupportedLangs。
type Lang string

// NewsDetail 詳細レスポンス。title / summary / body は指定 lang の翻訳由来。
type NewsDetail struct {
	ArticleID   string    `json:"article_id"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`

	// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
	// news 側では永続化と公開 API で同値を引き継ぐ。
	Source Source `json:"source"`

	// SourcePublishedAt 元記事 RSS 由来。nullable。
	SourcePublishedAt *time.Time `json:"source_published_at,omitempty"`
	SourceURL         string     `json:"source_url"`
	Summary           string     `json:"summary"`
	Tags              []string   `json:"tags"`
	Title             string     `json:"title"`
}

// NewsListItem 一覧レスポンス要素。title / summary は指定 lang の翻訳由来。body / source_url は含まない。
type NewsListItem struct {
	// ArticleID ULID。
	ArticleID string `json:"article_id"`

	// PublishedAt アプリ内で公開された日時 (承認時刻)。公開中記事では必ず値を持つ。
	PublishedAt time.Time `json:"published_at"`

	// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
	// news 側では永続化と公開 API で同値を引き継ぐ。
	Source Source `json:"source"`

	// SourcePublishedAt 元記事 (RSS 由来) の公開日時。nullable。
	SourcePublishedAt *time.Time `json:"source_published_at,omitempty"`
	Summary           string     `json:"summary"`
	Tags              []string   `json:"tags"`
	Title             string     `json:"title"`
}

// NewsListResponse defines model for NewsListResponse.
type NewsListResponse struct {
	Articles []NewsListItem `json:"articles"`
}

// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
// news 側では永続化と公開 API で同値を引き継ぐ。
type Source string

// LangQuery 対応言語コード。SSoT は news 内の domain.SupportedLangs。
type LangQuery = Lang

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// ListNewsParams defines parameters for ListNews.
type ListNewsParams struct {
	// Lang 翻訳言語。未指定・対応外は 400。
	Lang LangQuery `form:"lang" json:"lang"`

	// Limit 取得件数 (1-100)。未指定・範囲外は 400。
	Limit int `form:"limit" json:"limit"`
}

// GetNewsDetailParams defines parameters for GetNewsDetail.
type GetNewsDetailParams struct {
	// Lang 翻訳言語。未指定・対応外は 400。
	Lang LangQuery `form:"lang" json:"lang"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListNews request
	ListNews(ctx context.Context, params *ListNewsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNewsDetail request
	GetNewsDetail(ctx context.Context, articleId string, params *GetNewsDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListNews(ctx context.Context, params *ListNewsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNewsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNewsDetail(ctx context.Context, articleId string, params *GetNewsDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNewsDetailRequest(c.Server, articleId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListNewsRequest generates requests for ListNews
func NewListNewsRequest(server string, params *ListNewsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/news")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lang", params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNewsDetailRequest generates requests for GetNewsDetail
func NewGetNewsDetailRequest(server string, articleId string, params *GetNewsDetailParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "articleId", articleId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/news/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lang", params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListNewsWithResponse request
	ListNewsWithResponse(ctx context.Context, params *ListNewsParams, reqEditors ...RequestEditorFn) (*ListNewsResponse, error)

	// GetNewsDetailWithResponse request
	GetNewsDetailWithResponse(ctx context.Context, articleId string, params *GetNewsDetailParams, reqEditors ...RequestEditorFn) (*GetNewsDetailResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type ListNewsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NewsListResponse
}

// Status returns HTTPResponse.Status
func (r ListNewsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNewsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListNewsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetNewsDetailResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NewsDetail
}

// Status returns HTTPResponse.Status
func (r GetNewsDetailResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNewsDetailResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetNewsDetailResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListNewsWithResponse request returning *ListNewsResponse
func (c *ClientWithResponses) ListNewsWithResponse(ctx context.Context, params *ListNewsParams, reqEditors ...RequestEditorFn) (*ListNewsResponse, error) {
	rsp, err := c.ListNews(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNewsResponse(rsp)
}

// GetNewsDetailWithResponse request returning *GetNewsDetailResponse
func (c *ClientWithResponses) GetNewsDetailWithResponse(ctx context.Context, articleId string, params *GetNewsDetailParams, reqEditors ...RequestEditorFn) (*GetNewsDetailResponse, error) {
	rsp, err := c.GetNewsDetail(ctx, articleId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNewsDetailResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseListNewsResponse parses an HTTP response from a ListNewsWithResponse call
func ParseListNewsResponse(rsp *http.Response) (*ListNewsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNewsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NewsListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetNewsDetailResponse parses an HTTP response from a GetNewsDetailWithResponse call
func ParseGetNewsDetailResponse(rsp *http.Response) (*GetNewsDetailResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNewsDetailResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NewsDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
