// Package apinews provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apinews

import (
	"time"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for Lang.
const (
	LangEn Lang = "en"
	LangJa Lang = "ja"
)

// Valid indicates whether the value is a known member of the Lang enum.
func (e Lang) Valid() bool {
	switch e {
	case LangEn:
		return true
	case LangJa:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	SourceAws         Source = "aws"
	SourceAzure       Source = "azure"
	SourceGoogleCloud Source = "google-cloud"
	SourceOci         Source = "oci"
	SourceOther       Source = "other"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case SourceAws:
		return true
	case SourceAzure:
		return true
	case SourceGoogleCloud:
		return true
	case SourceOci:
		return true
	case SourceOther:
		return true
	default:
		return false
	}
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Lang 対応言語コード。SSoT は news 内の domain.SupportedLangs。
type Lang string

// NewsDetail 詳細レスポンス。title / summary / body は指定 lang の翻訳由来。
type NewsDetail struct {
	ArticleID   string    `json:"article_id"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`

	// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
	// news 側では永続化と公開 API で同値を引き継ぐ。
	Source Source `json:"source"`

	// SourcePublishedAt 元記事 RSS 由来。nullable。
	SourcePublishedAt *time.Time `json:"source_published_at,omitempty"`
	SourceURL         string     `json:"source_url"`
	Summary           string     `json:"summary"`
	Tags              []string   `json:"tags"`
	Title             string     `json:"title"`
}

// NewsListItem 一覧レスポンス要素。title / summary は指定 lang の翻訳由来。body / source_url は含まない。
type NewsListItem struct {
	// ArticleID ULID。
	ArticleID string `json:"article_id"`

	// PublishedAt アプリ内で公開された日時 (承認時刻)。公開中記事では必ず値を持つ。
	PublishedAt time.Time `json:"published_at"`

	// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
	// news 側では永続化と公開 API で同値を引き継ぐ。
	Source Source `json:"source"`

	// SourcePublishedAt 元記事 (RSS 由来) の公開日時。nullable。
	SourcePublishedAt *time.Time `json:"source_published_at,omitempty"`
	Summary           string     `json:"summary"`
	Tags              []string   `json:"tags"`
	Title             string     `json:"title"`
}

// NewsListResponse defines model for NewsListResponse.
type NewsListResponse struct {
	Articles []NewsListItem `json:"articles"`
}

// Source 記事のソース種別。SSoT は newsfeed 側の cloud_news_sources。
// news 側では永続化と公開 API で同値を引き継ぐ。
type Source string

// LangQuery 対応言語コード。SSoT は news 内の domain.SupportedLangs。
type LangQuery = Lang

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// ListNewsParams defines parameters for ListNews.
type ListNewsParams struct {
	// Lang 翻訳言語。未指定・対応外は 400。
	Lang LangQuery `form:"lang" json:"lang"`

	// Limit 取得件数 (1-100)。未指定・範囲外は 400。
	Limit int `form:"limit" json:"limit"`
}

// GetNewsDetailParams defines parameters for GetNewsDetail.
type GetNewsDetailParams struct {
	// Lang 翻訳言語。未指定・対応外は 400。
	Lang LangQuery `form:"lang" json:"lang"`
}
